spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://host.docker.internal:5432/sampleapp}
    username: ${DB_USERNAME:dbuser}
    password: ${DB_PASSWORD:}
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
